apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30036
    name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: forgerock-api
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: '6379'
        - name: WORK_QUEUE
          value: task-queue
      restartPolicy: Always
