# Stage 1 - Base Image
FROM node AS base
WORKDIR /worker

# Stage 2 - Install All Dependencies 
FROM base AS dependencies
COPY package*.json ./
RUN npm install

# Stage 3 - Build
FROM dependencies AS build
WORKDIR /worker
COPY . /worker
RUN npm run build

# Stage 4 - Release
FROM node:8.9-alpine AS release
WORKDIR /worker
COPY --from=dependencies /worker/package.json ./
RUN npm install --only=production
COPY --from=build /worker ./
EXPOSE 8080
CMD ["npm", "run", "start"]